### ISSUE TITLE
[BUG]: gets stuck after `❖ Successfully upgraded repo packages`

### ISSUE THREAD

**Issue by ThatOneCalculator** [crystal-linux/amethyst#100]
### Describe the bug

Ame gets stuck after `❖ Successfully upgraded repo packages`, until I ctrl + c. `yay`/etc work fine.

### To reproduce the bug

1. `ame` or `ame u`
2. observe

### Expected behavior

Ends/updates AUR

### Screenshots

```
➜  ~ ame
❖ Performing system upgrade
doas (kainoa@catalina) password: 
:: Synchronizing package databases...
 endeavouros is up to date
 testing is up to date
 core is up to date
 fcgu is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: adwaita-icon-theme: local (43.0-0.1) is newer than extra (43-1)
warning: gnome-desktop: local (1:43.0-0.1) is newer than extra (1:43-1)
warning: gnome-desktop-4: local (1:43.0-0.1) is newer than extra (1:43-1)
warning: gnome-desktop-common: local (1:43.0-0.1) is newer than extra (1:43-1)
 there is nothing to do
❖ Successfully upgraded repo packages
```

### Additional context

Arch Linux (vanilla, not crystal)

**Comment by fries1234** [comment]
hi, we moved over to gitlab (https://git.getcryst.al/crystal/software/amethyst), so it would be best to move the issue over there. (github account signin is supported if you need that)

**Comment by SomethingGeneric** [comment]
Silly question, you say it's on Arch, and yet I see `endeavouros is up to date` in the output.

Also, as fries said, please reopen on GitLab

**Comment by fries1234** [comment]
endeavouros is basically an arch distro. just easier to install.

**Comment by fries1234** [comment]
they dont hold back packages like manjaro, they use the same repos as arch.

**Comment by SomethingGeneric** [comment]
It's still worth noting that's it *not* actually Arch imo

**Comment by fries1234** [comment]
yeah i guess its not *exactly* arch

**Comment by ThatOneCalculator** [comment]
Sorry I didn't see this till now, I'll have to make a new gitlab. 

I mostly did endeavour since my old arch got borked and I needed a new install fast, it was with all minimal options and I built pacman from source after so there's nothing in there special except an extra repo.
