### ISSUE TITLE
[BUG]: Amethyst takes a long time checking AUR

### ISSUE THREAD

**Issue by lfom** [crystal-linux/amethyst#101]
### Describe the bug

Hi, there.

Thanks for creating and maintaining Crystal Linux and all its tools. Currently my daily driver is Garuda Gnome (I have installed it long before Crystal was available) and I was checking alternatives for `paru`, so I decided to try `ame` using the AUR package. But, for some reason, it always takes a long time checking AUR. I searched the repo and found #20, but either it was much worse in the past or simply it is not working as it should here.

Is it a problem with the AUR package, something needs to be changed in the config file or a known bug?

Regards

### To reproduce the bug

1. Install `ame`
2. Run `ame`
3. `ame` takes a long time checking AUR

### Expected behavior

Step 3 above should not take too long. At least here, `paru` is very fast, almost as fast as when checking the stock repositories.

### Screenshots

N/A

### Additional context

```
$ ame --version
Amethyst 4.0.3 (Funky Fish)

$ cat ~/.config/ame/config.toml                              
# See https://getcryst.al/docs/amethyst/config for more information on config keys

[base]
pacdiff_warn = true

[bin]
sudo = 'sudo'

$ time paru
:: Synchronizing package databases...
 garuda is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: packages not in the AUR: muonssh
 there is nothing to do
paru  1,68s user 0,08s system 59% cpu 2,948 total


$ time ame 
❖ Performing system upgrade
:: Synchronizing package databases...
 garuda is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
❖ Successfully upgraded repo packages
! Could not find the remote package for muonssh
❖ No upgrades available for installed AUR packages
❖ Scanning for .pacnew files post-upgrade
  No .pacnew files found                                                                                                                                                                                       
ame  2,60s user 0,15s system 7% cpu 38,186 total



```

**Comment by mchalunderscore** [comment]
Hi, sorry, we're primarily located on our selfhosted GitLab now, please re-open this issue at https://git.getcryst.al/crystal/software/amethyst !

**Comment by lfom** [comment]
@not-my-segfault 
Hmm, then this is another thing I would suggest: doing this requires creating an account there too, right? Please consider using a mirror on GitHub or plain GitLab and use it for issues, probably doing it this way will make it easier to add feedback.

**Comment by mchalunderscore** [comment]
> @not-my-segfault Hmm, then this is another thing I would suggest: doing this requires creating an account there too, right? Please consider using a mirror on GitHub or plain GitLab and use it for issue, probably it will get much more feedback this way.

We have support for using GitHub as an OAuth provider (so no new account needed!), however we are planning to eventually mirror our GitLab repos to the ones here on GitHub :smile:

**Comment by lfom** [comment]
Moved to https://git.getcryst.al/crystal/software/amethyst/-/issues/100
