### ISSUE TITLE
[BUG]: Timeout issue

### ISSUE THREAD

**Issue by jkw** [crystal-linux/amethyst#107]
### Describe the bug

New install, wanted to try out Amethyst for the first time since I'm used to yay.

Just typed: ame

Updates started etc. Then since it got stuck on `❖ Successfully upgraded repo packages`, I knew something was off.

### To reproduce the bug

1. Installed clean Crystal for the first time.
2. Opened terminal and wrote `ame`

### Expected behavior

Update and then done.

### Additional context

Did some debugging and found:

```
jkw@Odin ~]$ ame install -v update-grub
⌘ Cleaned: ["update-grub"]
  Into: ["update-grub"]
⌘ Initialized alpm handler
⌘ Sorting: "update-grub"
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Rpc(HTTP(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("aur.archlinux.org")), port: None, path: "/rpc/", query: Some("arg%5B%5D=update-grub&v=5&type=info"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 110, kind: TimedOut, message: "Connection timed out" })) }))
Location: src/internal/sort.rs:16

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: ame::internal::sort::sort with input=["update-grub"] options=Options { noconfirm: false, quiet: false, asdeps: false, upgrade: false }
      at src/internal/sort.rs:6
   1: ame::cmd_install with args=InstallArgs { packages: ["update-grub"], aur: false, repo: false, search: false, by: None } options=Options { noconfirm: false, quiet: false, asdeps: false, upgrade: false }
      at src/main.rs:78

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by axtloss** [comment]
This isn't an issue with amethyst. It's getting a timeout since the aur is currently offline, once it's back up amethyst should work normally.

**Comment by jkw** [comment]
Ah, my bad, you're right.
It works fine now.
But maybe toss a error message to the user that AUR is offline instead of just timeout?

**Comment by axtloss** [comment]
Amethyst does not now why it's unable to connect, all it knows is that the connection times out, it would not really be possible to know if the aur is down or it's an issue on the users end
