### ISSUE TITLE
Only prompt a user once about vim knowledge 

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/amethyst#13]
I mean idk what else to say, I think the hint is nice the first time `pacdiff` is needed, but it could get redundant.

**Comment by SomethingGeneric** [comment]
Hey @not-my-segfault idk if you're planning on making a config but i don't think an envvar is the best solution for this

**Comment by not-my-segfault** [comment]
> Hey @not-my-segfault idk if you're planning on making a config but i don't think an envvar is the best solution for this

3.6.0 actually implements this as a config so dw lol

**Comment by SomethingGeneric** [comment]
Oh sweet
