### ISSUE TITLE
[FEATURE]: ame query should only grep package names

### ISSUE THREAD

**Issue by SomethingGeneric** [crystal-linux/amethyst#18]
### Is your feature request related to a problem? Please describe.

It's not super helpful to have to `ame query linux | grep <some repo>` to just get package names. `linux` is a good arg example since it hits tons of packages in their description fields

### Describe the solution you'd like

Maybe a flag to enable searching descriptions too?

### Describe alternatives you've considered

I can't think of a use-case where ignoring desc as search criteria would be bad, but maybe there is one?

**Comment by SomethingGeneric** [comment]
On second thought the other issue I was going to open is basically the same, but for `search`. When I search `linux`, for example, I think ame should assume i mean only in the package name, at least by default.

**Comment by not-my-segfault** [comment]
IMO alternatively we should just let the user know you can use regex to search somehow, maybe in the `ame help` prompt

**Comment by not-my-segfault** [comment]
Although it seems we can only use regex for repo searches, for AUR searches, we could add a `--by/-b` flag to search by specific values

![image](https://user-images.githubusercontent.com/30374463/186825281-e26e5999-6059-41cd-a875-43606c7a7174.png)

**Comment by SomethingGeneric** [comment]
Oooo I like that approach. I suppose my lazy ass can get by with a shell alias. Did I see you start on that already?

**Comment by not-my-segfault** [comment]
> Oooo I like that approach. I suppose my lazy ass can get by with a shell alias. Did I see you start on that already?

I've actually made my own parser for searching packages, and it's currently just by name by default. Check out search results in the development branch when you have the time!
