### ISSUE TITLE
[FEATURE]: Customize how fast amethyst queries the AUR

### ISSUE THREAD

**Issue by exalented** [crystal-linux/amethyst#20]
### Is your feature request related to a problem? Please describe.

Amethyst is slow to query the aur for upgrades and waits for version information before continuing.

### Describe the solution you'd like

By being able to make multiple requests at a time this could cut down the time it takes to perform AUR upgrades. Make this a variable so that the user can specify how intensely they want to query the AUR to compare versions.

### Describe alternatives you've considered

Wait.

### Additional context

https://github.com/crystal-linux/amethyst/blob/683fc6bf3bbae05cbf2a687a02a6ef3a2e67816c/src/operations/upgrade.rs#L109

**Comment by not-my-segfault** [comment]
This is actually planned to be addressed soon, as our current plans with Amethyst is to:
- Polish out the current feature set, then
- Implement async RPC and searching/querying for Amethyst v4.0.0

We will most likely have it be a sane default, e.g. 4 concurrent queries, but we may make it configurable too as we've just implemented a `.config/ame/config.toml` file in v3.6.0 (PR #19)

**Comment by Trivernis** [comment]
> This is actually planned to be addressed soon, as our current plans with Amethyst is to:
> 
>     * Polish out the current feature set, then
> 
>     * Implement async RPC and searching/querying for Amethyst v4.0.0
> 
> 
> We will most likely have it be a sane default, e.g. 4 concurrent queries, but we may make it configurable too as we've just implemented a `.config/ame/config.toml` file in v3.6.0 (PR #19)

You can query package info for multiple packages at once in one request so we don't actually need to run several concurrent requests.
