### ISSUE TITLE
[BUG]: Amethyst shows packages rather than package when upgrading single packages

### ISSUE THREAD

**Issue by orowith2os** [crystal-linux/amethyst#25]
### Describe the bug

When I got to upgrade, it'll show "packages" rather than "package" when I need to update just one app.

### To reproduce the bug

1. Have only one out-of-date AUR package
2. `ame` or `ame upg`

### Expected behavior

Spelling would be correct and show "package" when only one package is needing to be updated

### Screenshots

https://cdn.discordapp.com/attachments/843147448917950485/1013695959273848842/unknown.png

**Comment by not-my-segfault** [comment]
We leave it this way for brevity's sake, we could adjust it to say package(s) if need be, but I feel like it's ultimately pointless implementing an entire check just for this and it would hurt progress with locales later too

**Comment by orowith2os** [comment]
That makes sense. Might be best just to set it to package(s), so that nothing's affected, then.

**Comment by not-my-segfault** [comment]
Assigned @Trivernis as I know he's working on Amethyst v4.0.0 right now
