### ISSUE TITLE
Install fails because I *didn't* remove build depends??

### ISSUE THREAD

**Issue by ihatethefrench** [crystal-linux/amethyst#4]
Or am I missing something else perhaps?
![ameissue18](https://user-images.githubusercontent.com/30374463/171192818-acbb2b4e-3e42-485b-9c72-d6228280d53f.png)

Issue first opened by @SomethingGeneric

**Comment by morbhead** [comment]
that's very strange? especially since amethyst doesn't handle uninstalling makedepends, *makepkg* does. i'll look into it when i can

**Comment by morbhead** [comment]
iirc saying no for the pacman prompt of uninstallation returns a non-zero returncode, which thinks ame that pacman didn't run properly, ame should prompt the user if they want to remove the dependencies themselves and then launch pacman with --noconfirm

Comment by @axtloss

**Comment by morbhead** [comment]
@morbhead ngnhngnhgn issue #1 still existing

Comment by @SomethingGeneric

**Comment by morbhead** [comment]
the problem is that makepkg already does the uninstalling of makedepends VERY smartly, but i do have *some* idea on how i could fix this

**Comment by morbhead** [comment]
^ @morbhead do it

Comment by @SomethingGeneric

**Comment by ihatethefrench** [comment]
This no longer happens due to a change introduced a while back, closing issue
