### ISSUE TITLE
[FEATURE]: Install from source of Github

### ISSUE THREAD

**Issue by diogopessoa** [crystal-linux/amethyst#53]
### Is your feature request related to a problem? Please describe.

Not everyone is familiar with Github, and doesn't know how to install ame from source.

### Describe the solution you'd like

Please insert in README.MD, how to install Amethyst on Arch Linux or derivatives.

### Describe alternatives you've considered

thanks!

**Comment by SomethingGeneric** [comment]
@not-my-segfault i'm happy to update the `README`, what branch would be best to base off of? Main?

**Comment by not-my-segfault** [comment]
> @not-my-segfault i'm happy to update the `README`, what branch would be best to base off of? Main?

Main is fine for this, yeah!

**Comment by SomethingGeneric** [comment]
Sweet!

**Comment by diogopessoa** [comment]
thanks guys for your feedback!

**Comment by mrshmllow** [comment]
github already has a default branch thing
