### ISSUE TITLE
Amethyst continues to upgrade aur packages even though pacman prompt was declined

### ISSUE THREAD

**Issue by axtloss** [crystal-linux/amethyst#6]
When upgrading the system using `ame` or `ame upg`, pacman asks the user if they want to continue with upgrading the listed packages, however, when declining the upgrade amethyst continues with upgrading aur packages.

It would be better if amethyst would also quit when declining the pacman prompt.

**Comment by ihatethefrench** [comment]
Maybe it could prompt if it should still attempt to upgrade from AUR?

**Comment by axtloss** [comment]
Yeah sounds good
