### ISSUE TITLE
[RFC]: Hide the AUR behind a CLI argument, or an additional y/n menu

### ISSUE THREAD

**Issue by orowith2os** [crystal-linux/amethyst#62]
### Date proposed

09/17/2022

### Short summary

Currently, Amethyst searches the AUR on every operation if the official repositories don't have a package available. 

### Motivation

The AUR is a collection of user-made scripts, and isn't always thoroughly verified by users before installation. Having Amethyst notify the user of the drawbacks of the AUR before using it would mitigate this slightly.

### Changes

Before checking the AUR for packages to install, use an additional `y/n` menu (which would ideally default to N, but probably best to set it to Y instead) before checking the AUR for packages to install/using the search function. 

This wouldn't affect the updating mechanism for AUR packages, only installation, and possibly searching.

### Drawbacks

It would make the process for installing AUR packages slightly more involved, but not by much.

### Alternatives

Blocking the AUR functionality in a configuration file would work as well, or have it enabled during the build process. The latter would allow for distributions to use Amethyst, without needing to worry about supporting the AUR.

If the AUR is disabled in Amethyst during build-time, the `ame -h/-v` command would show a note about it not having AUR functionality.

### Unanswered questions

*no response*

**Comment by fries1234** [comment]
im fine with the extra y/n menu warning users and stuff. all tho id say there should be a config option to disable that prompt in the config if you know the risks.
