### ISSUE TITLE
[FEATURE REQUEST]: Don't continue on to upgrading AUR packages if repo upgrade fails

### ISSUE THREAD

**Issue by orowith2os** [crystal-linux/amethyst#66]
### Describe the bug

Currently, Amethyst will attempt to upgrade its AUR packages if the repo update fails, such as due to a network error. This shouldn't be the case.

### To reproduce the bug

Run `ame upg` without internet access

Amethyst will proceed to fail to upgrade the repo packages, but then ask to try upgrading the AUR packages.

### Expected behavior

It should notify the user of a potential network error, and refuse to move onto upgrading the AUR.

### Screenshots

![image](https://user-images.githubusercontent.com/93224879/191025796-36866a2c-63e0-412b-92a2-388df11e5a59.png)

**Comment by axtloss** [comment]
amethyst should be asking you if you want to continue upgrading aur packages, regardless of if it failed or not, shouldn't that be enough?

**Comment by orowith2os** [comment]
It's probably best to not ask to upgrade AUR packages on a network error. It'll *be fine* normally, but it's not ideal.

**Comment by axtloss** [comment]
well wouldn't the user see that there was a network error and then decline the aur upgrade?

**Comment by orowith2os** [comment]
They probably would, but why make a prompt to update the AUR when the repo check failed with a network error?

**Comment by axtloss** [comment]
I wasn't trying to argue against the request, I actually agree with you that the upgrade should fail, I was just explaining what amethyst currently does, sorry if it came over the wrong way

**Comment by orowith2os** [comment]
Actually, maybe this would be better fit as a feature request, since it's not really a bug, and more of a design of how Amethyst was made.

**Comment by not-my-segfault** [comment]
The could not resolve host error could be as a result of stale cached DNS, so we can't be sure if it's a user connection error

**Comment by SomethingGeneric** [comment]
@not-my-segfault it should still `set -e` imho tho. If the package manager fails on the safer (non-AUR) upgrades, then something's funky. Not the best time to be doing builds and `pacman -U`

**Comment by fries1234** [comment]
![image](https://user-images.githubusercontent.com/80879058/191666083-f24e3abe-c081-4325-bfe6-b59c5d3f49d8.png)
what do yall think of this?

**Comment by fries1234** [comment]
*also i should switch off the i18n branch lol as that got merged*
