### ISSUE TITLE
[RFC]: Warn about package interventions before upgrade (news)

### ISSUE THREAD

**Issue by fries1234** [crystal-linux/amethyst#68]
### Date proposed

09/21/2022

### Short summary

I would like amethyst to warn about package interventions before an upgrade. Kind of like `eselect news`.

### Motivation

Sometimes, Arch might have a manual package intervention that you would have to do to upgrade. These are posted on the arch website, which sometimes you might forget to check before upgrading your system. Having the program warn you about package interventions before upgrading if there's a new news post up would be nice as it makes life a lot easier.

### Changes

Arch has an [RSS feed](https://archlinux.org/feeds/news/) for their news posts. We could use this feed and check if there's a new post and tell the user about it. We would have to find a way to store if the user has read the post or not so the program wont warn you if there's a new news post if you already read the news post.

### Drawbacks

I guess extra prompts you have to go through before an ugprade.

### Alternatives

Not that I know of.

### Unanswered questions

I don't have any unanswered questions.

**Comment by not-my-segfault** [comment]
This is incorrectly tagged, RFCs are project-wide, potentially controversial decisions, please reopen this as a FEATURE request (I do like the idea though!)

**Comment by mrshmllow** [comment]
also dont tag like 7 people off the bat like that
