### ISSUE TITLE
[BUG]: panics using gencomp

### ISSUE THREAD

**Issue by mrshmllow** [crystal-linux/amethyst#70]
### To reproduce the bug

1. use -G
2. Cry

### Expected behavior

comps are gen'ed

### Screenshots

![image](https://user-images.githubusercontent.com/40532058/191679040-db14e849-d49d-4a35-aa48-5d97a985a879.png)

**Comment by fries1234** [comment]
ive been testing and ngl idk whats wrong

using my debugger it seems to crash when it executes the `shell.generate()` function so i guess someone whos smarter then me can try to start looking there to try to fix it. and we are using clap 4 rc.1 so it might be a clap bug but idk

**Comment by mrshmllow** [comment]
We shouldnt be using non-stable libraries

**Comment by Trivernis** [comment]
Can you test if clap rc2 solves this issue?

**Comment by mrshmllow** [comment]
that isnt a thing

**Comment by Trivernis** [comment]
I think we need to debug this then
I'll check this weekend
Maybe it's not a clap issue but they just changed the arguments they require for autocompletion
