### ISSUE TITLE
[FEATURE]: Ability to view PKGBUILDS

### ISSUE THREAD

**Issue by marek-lach** [crystal-linux/amethyst#76]
### Is your feature request related to a problem? Please describe.

Sometimes the user wants to verify, or perhaps learn how a PKGBUILD is written.

### Describe the solution you'd like

For each searched/listed package, there should be an ability to view for example by pressing [W] its PKGBUILD file, so that if the user wants they can optionally have a look at it and review if it meets their requirements.

### Describe alternatives you've considered

One could manually search this through the aur website, but viewing PKGBUILDs through the command line with the help of an AUR helper would be much more convenient.

### Additional context

AUR helpers like auracle had this feature with the command show <package-name>, but it's no longer updated.

**Comment by axtloss** [comment]
This feature is already implemented in amethyst, it asks you if you want to verify the pkgbuilds.
