### ISSUE TITLE
[FEATURE]: Polkit

### ISSUE THREAD

**Issue by mrshmllow** [crystal-linux/amethyst#91]
### Is your feature request related to a problem? Please describe.

be cool to have agnostic ways to elevate that integrates well with the desktop

### Describe the solution you'd like

polkit

### Describe alternatives you've considered

none

**Comment by Trivernis** [comment]
Does a cli tool really need to integrate with the desktop?

**Comment by axtloss** [comment]
Using polkit is just as simple as setting the sudo binary path in the config to polkit, not sure what would be a special feature here.
also I agree with Julius, cli tools don't need to integrate with the desktop, polkit also doesn't have the best implementation when using it from a tty which is why sticking to sudo is better.

**Comment by mrshmllow** [comment]
systemd does it, and we're a gtky distro anyway might as well go all the way

**Comment by Trivernis** [comment]
As it can already be set in the config I'd say we should test how it behaves.
Keep in mind that ame is also distributed in the aur and should work inside all kinds of environments, even plain ttys.

**Comment by axtloss** [comment]
> systemd does it, and we're a gtky distro anyway might as well go all the way

just because one program does it, doesn't mean that every program should do it

**Comment by mrshmllow** [comment]
> Using polkit is just as simple as setting the sudo binary path in the config to polkit, not sure what would be a special feature here.

How?

**Comment by fries1234** [comment]
using `pkexec`

**Comment by axtloss** [comment]
> > Using polkit is just as simple as setting the sudo binary path in the config to polkit, not sure what would be a special feature here.
> 
> How?

![image](https://user-images.githubusercontent.com/60044824/194004867-260abb9c-8080-4514-8321-0c00f4ce6ae8.png)

**Comment by axtloss** [comment]
Tested it and it works without any issues, so nothing to add in amethyst

**Comment by Trivernis** [comment]
What we could do is adding a section to the docs that mentioned how to use polkit instead if sudo

**Comment by Trivernis** [comment]
Simular to how the arch wiku lists tips and tricks, and xommon issues at the bottom of wiki pages

**Comment by axtloss** [comment]
> What we could do is adding a section to the docs that mentioned how to use polkit instead if sudo

I don't think that's needed, the config option is right there and it's not very different compared to setting it to doas

**Comment by mrshmllow** [comment]
I have read the entire arch page, read a lot of the reference manual and somehow it didnt mention a single thing about pkexec until i asked

**Comment by mrshmllow** [comment]
> Tested it and it works without any issues, so nothing to add in amethyst

#92

**Comment by axtloss** [comment]
What am I supposed to do with that? I tested it and it works.
